name: benchrep-base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==2.4.4
      - pandas==3.0.2
      - scipy==1.17.1
      - scikit-learn==1.8.0
      - tqdm==4.67.3
      - biopython==1.87
      - matplotlib==3.10.8
      - seaborn==0.13.2
      - xgboost==3.2.0
      - python-Levenshtein==0.27.3
